[package]
name = "super-types"
description = "Types for the Super API"
version.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
repository.workspace = true
documentation.workspace = true
include = ["/src", "/README.md", "/LICENSE*"]

[features]
typescript = ["dep:ts-rs"]

[dependencies]
base64.workspace = true
url.workspace = true
chrono.workspace = true
hex.workspace = true
serde.workspace = true
sha2.workspace = true
uuid.workspace = true
ts-rs = { version = "12", optional = true, features = ["chrono-impl", "uuid-impl"] }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
